### ISSUE TITLE
Can't submit a poll

### ISSUE THREAD

**Issue by anlhord** [daryl/qstn#1]
clicking ask doesn't seem to work

**Comment by daryl** [comment]
What browser / version? Also have you filled in a question and at least 2 options?

**Comment by sorcix** [comment]
Ghostery breaks this.

**Comment by daryl** [comment]
Are you guys using Firefox 35.0? There's a bug that's pretty much unfixable. I may end up porting it over to React instead of Mithril, as that's probably a lot more stable.

**Comment by sorcix** [comment]
Firefox 34.0.5

When trying to create a new poll:
```
TypeError: this.entry.question(...) is undefined
TypeError: g.option(...) is undefined
```

**Comment by daryl** [comment]
Yeah that's it. I tried to fix it earlier, it's a weird one. The code works everywhere else but doesn't seem to work in that creation area. Not sure why. If any of you can work it out, let me know, otherwise I'm going to start rewriting stuff.

**Comment by daryl** [comment]
Turns out `innerText` is undefined in Firefox, had to change it to `textContent`.
